#!/bin/bash

##### Check the OS name #####


OS=`cat /etc/os-release | grep PRETTY_NAME= | awk -F'"' '{print$2}' | awk -F" " '{print$1}'`

if
  [ ${OS} = CentOS ]

then

echo -e "\n This system is centos \n"

elif
   [ ${OS} = Ubuntu ]

then
   echo -e "\n This is an ubuntu system\n"
elif
  [ ${OS} = debian ]
then
echo -e "\n This system is debian\n"
else
echo -e "\n system OS unknown\n"

fi